
exports.newWord = {
  wordList:["SUPERMAN", "BATMAN", "FLASH", "HAWKGIRL", "BATGIRL", "SUPERGIRL", "AQUAMAN", "CYBORG", "ROBIN", "NIGHTWING", "THOR", "DEADPOOL", "MYSTIQUE", "STORM", "GRODD", "MAGNETO", "LOKI", "STEEL", "GAMBIT", "ZOD"]
};